addons:
  apt:
    packages:
    - qt5-default
    - qtbase5-dev
    - qtdeclarative5-dev
    - libqt5webkit5-dev
    - libsqlite3-dev
    
script:
 - qmake -project
 - qmake LED-Controller.pro
 - make
